# Generated by Django 2.2.14 on 2022-12-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('SH', 'Short Hair'), ('MH', 'Medium Hair'), ('LH', 'Long Hair')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('LE', 'Low Energy'), ('ME', 'Medium Energy'), ('HE', 'High Energy')], max_length=2),
        ),
    ]
