# Generated by Django 2.2.14 on 2022-12-15 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221215_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('S', 'Small Size'), ('M', 'Medium Size'), ('L', 'Large Size')], default='NULL', max_length=1),
        ),
    ]
