# Generated by Django 2.2.14 on 2022-12-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20221215_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='status',
            new_name='available',
        ),
    ]
