# Generated by Django 2.2.14 on 2023-01-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_duration',
            field=models.IntegerField(default=0),
        ),
    ]
