# Generated by Django 2.2.14 on 2023-01-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20230102_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image2',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image3',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='image4',
            field=models.ImageField(default=False, upload_to=''),
            preserve_default=False,
        ),
    ]
