# Generated by Django 2.2.14 on 2023-01-05 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230105_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='rental_duration',
        ),
    ]
