# Generated by Django 2.2.14 on 2023-01-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_order_rental_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rental_duration',
            field=models.IntegerField(default=1),
        ),
    ]
